### ISSUE TITLE
BlueGreen example doesn't work 

### ISSUE THREAD

**Issue by alberttwong** [ffirg/openshift#5]
the image.php within https://github.com/ffirg/bluegreen.git is hard code to blue.

**Comment by alberttwong** [comment]
Maybe we should have 2 git projects.....?

**Comment by ffirg** [comment]
The idea is to change the code half way through the demo, so you can show
how the changes are done,
We could automate a git pull/push within the script to make the change but
perhaps it's better as a semi-manual demo?

**Comment by alberttwong** [comment]
ahh.. in that case I'll update the README.
